### ISSUE TITLE
大神，双引号有问题，能不能支持双引号

### ISSUE THREAD

**Issue by dream2023** [yisibl/postcss-aspect-ratio-mini#4]
如图，单引号编译出来是正常的，双引号编译出来会有单引号，能不能把双引号也支持一下

**Comment by yisibl** [comment]
没有看到图，请写出输入什么，期望输出什么？例如：
input:
```css

```

output:
```css
```

**Comment by dream2023** [comment]
> 没有看到图，请写出输入什么，期望输出什么？例如：
> input:
> 
> output:

抱歉打错字了，
input:
```
.aspect-box {
    aspect-ratio: "16:9";
}
```

output: 
```
.aspect-box:before {
    padding-top: 56.25%;
}
```

实际输出：
```
.aspect-box:before {
    padding-top: '56.25%';
}
```

也就是在双引号下，编译出来的代码会带上带引号，并不是有效的数值，希望在双引号下也能编译出有效的数值

**Comment by yisibl** [comment]
这个问题已经修复了，但 node 11.3.0 CI 有报错，我要看一下。

**Comment by dream2023** [comment]
> 这个问题已经修复了，但 node 11.3.0 CI 有报错，我要看一下。

OK，多谢大神~

npm仓库大神别忘更新一下

**Comment by yisibl** [comment]
好了，1.0.1 版本。
