### ISSUE TITLE
Update to match the upcoming native aspect-ratio syntax

### ISSUE THREAD

**Issue by equinusocio** [yisibl/postcss-aspect-ratio-mini#6]
The new CSS Sizing lv4 will introduce the native css `aspect-ratio` property:

https://drafts.csswg.org/css-sizing-4/#aspect-ratio

The valye syntax is a bit different, this regex `(((?:\d*\.?\d*)?)(?:\/|\|)(\d+))` should match the new `A/B` syntax. This is useful to polyfill the future syntax without rewriting the rule if the plugin is removed.

**Comment by yisibl** [comment]
Do you mean to switch the syntax of the current plugin to `aspect-ratio: 16/9`?

**Comment by equinusocio** [comment]
Yes, currently the plugin use `aspect-ratio: "16:9";` while the upcoming css syntax is `aspect-ratio: 16/9;`. In this way, this plugin can be used as "polyfill" of the native syntax until it will gain wide support.

Probably the best way to improve this is to allow both syntaxes to avoid breaking changes.

**Comment by yisibl** [comment]
Native CSS  `aspect-ratio` demo https://jsbin.com/kupebesidi/edit?html,css,output

**Comment by yisibl** [comment]
@equinusocio Please take a look at PR #7
